version: "3.8"
volumes:
  airdrops_pgadmin:
    name: airdrops_pgadmin
services:
  airdrops_db:
    build:
      dockerfile: db.dockerfile
    container_name: airdrops_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: airdrops
      POSTGRES_PASSWORD: password
    ports:
    - "5432:5432"
    volumes:
      - "./migrations-postgresql:/docker-entrypoint-initdb.d/" # Initialization scripts
    extra_hosts:
      - "host.docker.internal:host-gateway" # Enable using host.docker.internal from SAM on linux
  airdrops_pgadmin:
    image: dpage/pgadmin4:6.15
    logging:
      driver: none
    container_name: airdrops_pgadmin
    restart: always
    depends_on:
    - airdrops_db
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_DEFAULT_EMAIL: "admin@airdrops.network"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
    - "8000:80"